//remember this page will affect all the pages as it is RootLayout 

import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";


const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create school Management app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en" >
        <body>
          {children}
        </body>
      </html>
    
    
  )
  
}
