import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create school Management app",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className ="h-screen flex">

     {/*LEFT*/}
     <div className="w-1/6 bg-blue-50">L</div>
     {/*RIGHT*/}
     <div className = "w-5/6 bg-blue-200">R</div>
     
    </div>
  );
}
